import ForgeCore
import ForgeData
import Foundation

/// One modality-aware timeline for completed-workout detail and share images.
/// Logging rows generated by a conditioning/yoga block remain available to
/// analytics, but presentation treats the owning block as the user-visible
/// work instead of expanding its implementation rows as strength sets.
struct WorkoutPresentationPlan {
    enum Modality: String, Hashable {
        case strength
        case cardio
        case conditioning
        case yoga
    }

    struct LegacyConditioning: Identifiable {
        let id: UUID
        let position: Int
        let plan: ConditioningPlan
        let result: ConditioningResult?
    }

    enum Item: Identifiable {
        case exercise(WorkoutExerciseModel)
        case block(WorkoutBlockModel)
        case legacyConditioning(LegacyConditioning)
        case session(CardioSessionModel, position: Int)

        var id: UUID {
            switch self {
            case .exercise(let exercise): exercise.id
            case .block(let block): block.id
            case .legacyConditioning(let conditioning): conditioning.id
            case .session(let session, _): session.id
            }
        }

        var position: Int {
            switch self {
            case .exercise(let exercise): exercise.position
            case .block(let block): block.position
            case .legacyConditioning(let conditioning): conditioning.position
            case .session(_, let position): position
            }
        }
    }

    let items: [Item]
    let modalities: Set<Modality>
    let visibleExercises: [WorkoutExerciseModel]
    let strengthExercises: [WorkoutExerciseModel]

    var isMixed: Bool { modalities.count > 1 }

    var hasModalityBlocks: Bool {
        items.contains {
            switch $0 {
            case .block, .legacyConditioning: true
            case .exercise, .session: false
            }
        }
    }

    static func make(for workout: WorkoutModel) -> Self {
        let sessions = workout.cardioSessions.filter { $0.deletedAt == nil }
        let sessionByExerciseID = Dictionary(
            sessions.compactMap { session in
                session.workoutExerciseID.map { ($0, session) }
            },
            uniquingKeysWith: { first, _ in first }
        )
        var visibleExercises = workout.exercises.filter { $0.generatedByWorkoutBlockID == nil }
        var legacyConditioning: LegacyConditioning?

        let hasConditioningBlock = workout.blocks.contains { $0.kind == .conditioning }
        if !hasConditioningBlock,
           let plan = ConditioningPlan.decode(from: workout.conditioningPlanSnapshotJSON) {
            let movementExerciseIDs = Set(plan.sections.flatMap(\.movements).map(\.exerciseID))
            let movementRows = visibleExercises.filter { movementExerciseIDs.contains($0.exerciseID) }
            let position = movementRows.map(\.position).min()
                ?? visibleExercises.map(\.position).min()
                ?? 0
            visibleExercises.removeAll { movementExerciseIDs.contains($0.exerciseID) }
            legacyConditioning = LegacyConditioning(
                id: workout.id,
                position: position,
                plan: plan,
                result: ConditioningResult.decode(from: workout.conditioningResultJSON)
            )
        }

        var items = visibleExercises.map(Item.exercise)
            + workout.blocks.map(Item.block)
        if let legacyConditioning {
            items.append(.legacyConditioning(legacyConditioning))
        }

        // Imported/legacy sessions without an exercise or block have no authored
        // position. Keep their existing chronological order after positioned work.
        let unlinkedSessions = sessions
            .filter { session in
                guard session.workoutExerciseID == nil, session.workoutBlockID == nil else { return false }
                return !(session.isConditioningSession && legacyConditioning != nil)
            }
            .sorted { $0.startedAt < $1.startedAt }
        let trailingPosition = items.map(\.position).max() ?? -1
        items.append(contentsOf: unlinkedSessions.enumerated().map { offset, session in
            .session(session, position: trailingPosition + offset + 1)
        })

        items.sort {
            if $0.position != $1.position { return $0.position < $1.position }
            return $0.id.uuidString < $1.id.uuidString
        }
        visibleExercises.sort {
            if $0.position != $1.position { return $0.position < $1.position }
            return $0.id.uuidString < $1.id.uuidString
        }

        let modalities = Set(items.map { item -> Modality in
            switch item {
            case .exercise(let exercise):
                guard let session = sessionByExerciseID[exercise.id] else {
                    return YogaFlowPlan.decode(from: exercise.yogaFlowJSON) == nil ? .strength : .yoga
                }
                if session.isYogaSession { return .yoga }
                if session.isConditioningSession { return .conditioning }
                return .cardio
            case .block(let block):
                return block.kind == .yoga ? .yoga : .conditioning
            case .legacyConditioning:
                return .conditioning
            case .session(let session, _):
                if session.isYogaSession { return .yoga }
                if session.isConditioningSession { return .conditioning }
                return .cardio
            }
        })

        let strengthExercises = visibleExercises.filter { exercise in
            sessionByExerciseID[exercise.id] == nil
                && YogaFlowPlan.decode(from: exercise.yogaFlowJSON) == nil
        }
        return Self(
            items: items,
            modalities: modalities,
            visibleExercises: visibleExercises,
            strengthExercises: strengthExercises
        )
    }
}
