#!/usr/bin/env python3
"""Build ForgeFit's offline guided-yoga narration through OpenRouter.

The script deliberately separates four gates:

1. ``catalog`` is free and shows the exact transcript/asset workload.
2. ``audition`` is a small billable run across candidate voices.
3. ``batch`` refuses to run until the chosen female and male voices are
   explicitly marked as audition-approved.
4. ``verify`` checks every expected asset and is the only command that may
   mark the bundled manifest approved.

No pose text is generated by a model. Gemini narrates the reviewed words in
``ForgeFit/Resources/yoga_guidance.json`` exactly as authored.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import dataclasses
import hashlib
import html
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Iterable


MODEL = "google/gemini-3.1-flash-tts-preview"
OPENROUTER_URL = "https://openrouter.ai/api/v1"
HARD_SPEND_CAP_USD = 15.0
CREDIT_RESERVE_USD = 0.25
CREDIT_CHECK_INTERVAL_BATCHES = 20
GENERATION_ATTEMPTS = 6
SCHEMA_VERSION = 1

FEMALE_CANDIDATES = ("Vindemiatrix", "Achernar", "Sulafat", "Despina")
MALE_CANDIDATES = ("Orus", "Schedar", "Algieba", "Umbriel")

ROOT = Path(__file__).resolve().parents[1]
RESOURCE_DIR = ROOT / "ForgeFit" / "Resources"
GUIDANCE_PATH = RESOURCE_DIR / "yoga_guidance.json"
POSES_PATH = RESOURCE_DIR / "yoga_poses.json"
MANIFEST_PATH = RESOURCE_DIR / "yoga_audio_manifest.json"
AUDIO_DIR = RESOURCE_DIR / "YogaAudio"
ARTIFACT_DIR = ROOT / "artifacts" / "yoga-audio"
LEDGER_PATH = ARTIFACT_DIR / "generation-ledger.json"


class YogaAudioError(RuntimeError):
    pass


@dataclasses.dataclass(frozen=True)
class Transcript:
    clip_id: str
    text: str
    kind: str


@dataclasses.dataclass(frozen=True)
class GenerationTask:
    instructor: str
    voice: str
    transcript: str
    kind: str
    clip_ids: tuple[str, ...]
    filename: str
    estimated_cost: float


@dataclasses.dataclass(frozen=True)
class GenerationResult:
    task: GenerationTask
    duration_seconds: float
    sha256: str
    generation_id: str | None
    actual_cost: float | None


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=False)
        handle.write("\n")
    temporary.replace(path)


def resolve_side(text: str, side: str) -> str:
    opposite = "right" if side == "left" else "left"
    return text.replace("{side}", side).replace("{oppositeSide}", opposite)


def transcript_catalog() -> list[Transcript]:
    guidance = load_json(GUIDANCE_PATH)
    poses = {entry["slug"]: entry for entry in load_json(POSES_PATH)}
    if guidance.get("schemaVersion") != SCHEMA_VERSION:
        raise YogaAudioError("Unsupported yoga_guidance.json schema")

    result: list[Transcript] = []
    seen_ids: set[str] = set()

    def append(clip_id: str, text: str, kind: str) -> None:
        if not text.strip():
            raise YogaAudioError(f"Empty transcript: {clip_id}")
        if clip_id in seen_ids:
            raise YogaAudioError(f"Duplicate clip id: {clip_id}")
        if "{side}" in text or "{oppositeSide}" in text:
            raise YogaAudioError(f"Unresolved side placeholder: {clip_id}")
        seen_ids.add(clip_id)
        result.append(Transcript(clip_id=clip_id, text=text, kind=kind))

    for entry in guidance["poses"]:
        slug = entry["slug"]
        metadata = poses.get(slug)
        if metadata is None:
            raise YogaAudioError(f"Guidance references missing pose: {slug}")
        sides = ("left", "right") if metadata["unilateral"] else ("center",)
        announced_name = entry.get("nameAnnouncement", metadata["name"])
        for side in sides:
            suffix = f", {side} side." if side != "center" else "."
            append(f"pose.{slug}.name.{side}", announced_name + suffix, "poseName")

        cue_groups = (
            ("entry", "entry"),
            ("alignment", "alignment"),
            ("breath", "breath"),
            ("options", "option"),
            ("reflection", "reflection"),
        )
        for json_key, kind in cue_groups:
            for index, template in enumerate(entry["cues"][json_key]):
                is_sided = "{side}" in template or "{oppositeSide}" in template
                if is_sided:
                    if not metadata["unilateral"]:
                        raise YogaAudioError(f"Bilateral pose has a side placeholder: {slug}")
                    for side in ("left", "right"):
                        append(
                            f"pose.{slug}.{kind}.{index}.{side}",
                            resolve_side(template, side),
                            kind,
                        )
                else:
                    append(f"pose.{slug}.{kind}.{index}.shared", template, kind)

        exit_text = entry["cues"]["exit"]
        if "{side}" in exit_text or "{oppositeSide}" in exit_text:
            if not metadata["unilateral"]:
                raise YogaAudioError(f"Bilateral pose has a sided exit: {slug}")
            for side in ("left", "right"):
                append(f"pose.{slug}.exit.0.{side}", resolve_side(exit_text, side), "exit")
        else:
            append(f"pose.{slug}.exit.0.shared", exit_text, "exit")

    global_groups = (
        ("openings", "opening"),
        ("breath", "breath"),
        ("awareness", "awareness"),
        ("encouragement", "encouragement"),
        ("spiritual", "spiritual"),
        ("closings", "closing"),
    )
    for json_key, kind in global_groups:
        for index, line in enumerate(guidance["global"][json_key]):
            append(f"global.{kind}.{index}", line, kind)

    return result


def styled_input(text: str, kind: str) -> str:
    if kind in {"reflection", "spiritual", "awareness", "opening", "closing"}:
        tags = "[calm] [slow] [warm] [meditative] [gentle]"
    elif kind == "encouragement":
        # Gemini's preview endpoint has returned empty audio for short
        # encouragement lines when [slow] is combined with this voice. Keep
        # the spoken transcript exact while using the stable calm delivery.
        tags = "[calm] [warm] [gentle]"
    elif kind in {"entry", "alignment", "option", "exit", "poseName"}:
        tags = "[calm] [clear] [warm] [gentle]"
    else:
        tags = "[calm] [slow] [warm] [gentle]"
    return f"{tags} {text}"


def estimated_duration(text: str) -> float:
    return max(1.4, len(text.split()) / 2.25 + 0.45)


def estimated_cost(text: str) -> float:
    # Current live pricing is $1/M prompt tokens and $20/M output tokens.
    # Output audio tokenization is provider-dependent. Reserving 100 tokens
    # per estimated second is intentionally conservative for the hard cap.
    seconds = estimated_duration(text)
    prompt_tokens = max(1, len(styled_input(text, "entry")) / 4)
    return prompt_tokens / 1_000_000 + seconds * 100 * 20 / 1_000_000


def slugify(value: str, maximum: int = 104) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    return normalized[:maximum]


def output_filename(instructor: str, transcript: str, representative_id: str) -> str:
    digest = hashlib.sha256(transcript.encode("utf-8")).hexdigest()[:10]
    prefix = "f" if instructor == "female" else "m"
    return f"yoga_{prefix}_{slugify(representative_id)}_{digest}.mp3"


def build_tasks(
    female_voice: str,
    male_voice: str,
    transcripts: Iterable[Transcript] | None = None,
) -> list[GenerationTask]:
    transcripts = list(transcripts or transcript_catalog())
    grouped: dict[tuple[str, str], list[Transcript]] = {}
    for instructor in ("female", "male"):
        for transcript in transcripts:
            grouped.setdefault((instructor, transcript.text), []).append(transcript)

    tasks: list[GenerationTask] = []
    for (instructor, text), entries in grouped.items():
        first = entries[0]
        voice = female_voice if instructor == "female" else male_voice
        tasks.append(GenerationTask(
            instructor=instructor,
            voice=voice,
            transcript=text,
            kind=first.kind,
            clip_ids=tuple(entry.clip_id for entry in entries),
            filename=output_filename(instructor, text, first.clip_id),
            estimated_cost=estimated_cost(text),
        ))
    return sorted(tasks, key=lambda task: (task.instructor, task.clip_ids[0]))


def api_request(
    method: str,
    path: str,
    api_key: str,
    payload: dict[str, Any] | None = None,
    timeout: float = 120,
) -> tuple[bytes, Any]:
    body = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = urllib.request.Request(
        OPENROUTER_URL + path,
        data=body,
        method=method,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://forgefit.app",
            "X-Title": "ForgeFit Yoga Audio Builder",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return response.read(), response.headers
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise YogaAudioError(f"OpenRouter HTTP {error.code}: {detail[:500]}") from error
    except urllib.error.URLError as error:
        raise YogaAudioError(f"OpenRouter request failed: {error.reason}") from error


def require_api_key() -> str:
    key = os.environ.get("OPENROUTER_API_KEY", "").strip()
    if not key:
        raise YogaAudioError(
            "OPENROUTER_API_KEY is not set. Export it in this shell; the key is never written to disk."
        )
    return key


def credit_remaining(api_key: str) -> float | None:
    try:
        body, _ = api_request("GET", "/credits", api_key, timeout=30)
        data = json.loads(body).get("data", {})
        total = float(data.get("total_credits", 0))
        used = float(data.get("total_usage", 0))
        return max(0.0, total - used)
    except (YogaAudioError, ValueError, TypeError, json.JSONDecodeError):
        return None


def generation_cost(api_key: str, generation_id: str | None) -> float | None:
    if not generation_id:
        return None
    query = urllib.parse.urlencode({"id": generation_id})
    for attempt in range(6):
        if attempt:
            time.sleep(min(1 + attempt, 4))
        try:
            body, _ = api_request("GET", f"/generation?{query}", api_key, timeout=30)
            payload = json.loads(body).get("data", {})
            for key in ("total_cost", "cost"):
                if payload.get(key) is not None:
                    return float(payload[key])
        except (YogaAudioError, ValueError, TypeError, json.JSONDecodeError):
            continue
    return None


def run_checked(arguments: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(arguments, check=True, text=True, capture_output=True)


def normalize_audio(raw_path: Path, output_path: Path, *, raw_pcm: bool = False) -> None:
    if not shutil.which("ffmpeg"):
        raise YogaAudioError("ffmpeg is required for MP3 normalization")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    command = ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y"]
    if raw_pcm:
        # Gemini TTS returns headerless, little-endian signed 16-bit PCM at
        # 24 kHz mono. Declare those parameters explicitly so ffmpeg does not
        # have to guess the input container or sample format.
        command += ["-f", "s16le", "-ar", "24000", "-ac", "1"]
    command += [
        "-i", str(raw_path),
        "-af", "loudnorm=I=-18:TP=-2:LRA=7",
        "-ar", "24000", "-ac", "1", "-codec:a", "libmp3lame", "-b:a", "96k",
        str(output_path),
    ]
    try:
        run_checked(command)
    except subprocess.CalledProcessError as error:
        raise YogaAudioError(f"ffmpeg normalization failed: {error.stderr[-500:]}") from error


def probe_audio(path: Path) -> dict[str, Any]:
    if not shutil.which("ffprobe"):
        raise YogaAudioError("ffprobe is required for audio verification")
    try:
        result = run_checked([
            "ffprobe", "-v", "error", "-select_streams", "a:0",
            "-show_entries", "stream=codec_name,sample_rate,channels,duration:format=duration",
            "-of", "json", str(path),
        ])
        payload = json.loads(result.stdout)
    except (subprocess.CalledProcessError, json.JSONDecodeError) as error:
        raise YogaAudioError(f"Unreadable audio file: {path.name}") from error
    streams = payload.get("streams", [])
    if not streams:
        raise YogaAudioError(f"No audio stream: {path.name}")
    stream = streams[0]
    duration = float(stream.get("duration") or payload.get("format", {}).get("duration") or 0)
    return {
        "codec": stream.get("codec_name"),
        "sample_rate": int(stream.get("sample_rate") or 0),
        "channels": int(stream.get("channels") or 0),
        "duration": duration,
    }


def verify_signal(path: Path) -> None:
    try:
        result = subprocess.run(
            ["ffmpeg", "-hide_banner", "-i", str(path), "-af", "volumedetect", "-f", "null", "-"],
            check=False,
            text=True,
            capture_output=True,
        )
    except OSError as error:
        raise YogaAudioError("ffmpeg is required for signal verification") from error
    match = re.search(r"max_volume:\s+(-?inf|-?[0-9.]+) dB", result.stderr)
    if not match or match.group(1) == "-inf":
        raise YogaAudioError(f"Silent or unreadable audio: {path.name}")
    maximum = float(match.group(1))
    if maximum > -0.25:
        raise YogaAudioError(f"Audio may clip ({maximum:.2f} dB): {path.name}")


def generate_one(task: GenerationTask, api_key: str, output_dir: Path) -> GenerationResult:
    minimal_transcript = task.transcript
    if task.kind == "poseName" and minimal_transcript.endswith("."):
        # A trailing ellipsis avoids an empty-stream edge case on very short
        # pose names while preserving every spoken word and visible caption.
        minimal_transcript = minimal_transcript[:-1] + "..."
    delivery_inputs = tuple(dict.fromkeys((
        styled_input(task.transcript, task.kind),
        f"[calm] [warm] [gentle] {task.transcript}",
        styled_input(minimal_transcript, task.kind),
    )))
    payload = {
        "model": MODEL,
        "input": delivery_inputs[0],
        "voice": task.voice,
        # OpenRouter's Gemini adapter currently supports PCM output only.
        # The model emits raw 24 kHz, 16-bit, mono audio; normalize_audio
        # converts that byte stream into the MP3 files bundled by ForgeFit.
        "response_format": "pcm",
    }
    last_error: Exception | None = None
    for attempt in range(GENERATION_ATTEMPTS):
        try:
            # Preserve every spoken word, but simplify non-spoken delivery
            # tags after repeated empty responses from the preview model.
            payload["input"] = delivery_inputs[min(attempt // 2, len(delivery_inputs) - 1)]
            audio, headers = api_request("POST", "/audio/speech", api_key, payload=payload)
            if len(audio) < 1_024:
                raise YogaAudioError(f"Audio response was unexpectedly small ({len(audio)} bytes)")
            generation_id = headers.get("X-Generation-Id") or headers.get("x-generation-id")
            with tempfile.TemporaryDirectory(prefix="forgefit-yoga-") as temporary:
                raw = Path(temporary) / "raw.pcm"
                raw.write_bytes(audio)
                final = output_dir / task.filename
                normalize_audio(raw, final, raw_pcm=True)
            probe = probe_audio(output_dir / task.filename)
            if probe["duration"] <= 0.4:
                raise YogaAudioError("Generated clip is too short")
            verify_signal(output_dir / task.filename)
            digest = hashlib.sha256((output_dir / task.filename).read_bytes()).hexdigest()
            cost = generation_cost(api_key, generation_id)
            return GenerationResult(
                task=task,
                duration_seconds=probe["duration"],
                sha256=digest,
                generation_id=generation_id,
                actual_cost=cost,
            )
        except (YogaAudioError, OSError, subprocess.SubprocessError) as error:
            last_error = error
            if attempt < GENERATION_ATTEMPTS - 1:
                # Empty-but-successful media responses can occur during a
                # transient provider brownout. Stagger workers so the whole
                # batch does not immediately retry in lockstep.
                jitter = (sum(task.filename.encode("utf-8")) % 10) / 10
                time.sleep(min(2 ** attempt, 16) + jitter)
    raise YogaAudioError(
        f"Failed {task.clip_ids[0]} after {GENERATION_ATTEMPTS} attempts: {last_error}"
    )


def load_ledger() -> dict[str, Any]:
    if not LEDGER_PATH.exists():
        return {"model": MODEL, "budgetedSpendUSD": 0.0, "generations": []}
    payload = load_json(LEDGER_PATH)
    if payload.get("model") != MODEL:
        raise YogaAudioError("Generation ledger belongs to a different model")
    return payload


def completed_result(task: GenerationTask, ledger: dict[str, Any], output_dir: Path) -> GenerationResult | None:
    target = output_dir / task.filename
    for item in ledger.get("generations", []):
        if (
            item.get("instructor") == task.instructor
            and item.get("voice") == task.voice
            and item.get("transcript") == task.transcript
            and item.get("filename") == task.filename
            and target.exists()
        ):
            digest = hashlib.sha256(target.read_bytes()).hexdigest()
            if digest != item.get("sha256"):
                return None
            return GenerationResult(
                task=task,
                duration_seconds=float(item["durationSeconds"]),
                sha256=digest,
                generation_id=item.get("generationID"),
                actual_cost=item.get("actualCostUSD"),
            )
    return None


def ledger_item(result: GenerationResult) -> dict[str, Any]:
    return {
        "instructor": result.task.instructor,
        "voice": result.task.voice,
        "transcript": result.task.transcript,
        "kind": result.task.kind,
        "clipIDs": list(result.task.clip_ids),
        "filename": result.task.filename,
        "durationSeconds": round(result.duration_seconds, 4),
        "sha256": result.sha256,
        "generationID": result.generation_id,
        "estimatedCostUSD": round(result.task.estimated_cost, 6),
        "actualCostUSD": result.actual_cost,
    }


def calibrated_credit_projection(
    conservative_cost: float,
    ledger: dict[str, Any],
) -> tuple[float, float | None]:
    """Project account-credit needs from same-model recorded generations.

    ``estimatedCostUSD`` deliberately reserves far more audio tokens than
    Gemini normally reports. Keep using that conservative figure for the
    project's hard spend cap, but calibrate the separate account-balance
    check once OpenRouter has returned enough actual-cost evidence. A 1.25x
    multiplier and 50% floor preserve headroom if later clips cost more.
    """
    actual = 0.0
    estimated = 0.0
    for item in ledger.get("generations", []):
        actual_cost = item.get("actualCostUSD")
        estimated_cost = item.get("estimatedCostUSD")
        if actual_cost is None or estimated_cost is None or float(estimated_cost) <= 0:
            continue
        actual += float(actual_cost)
        estimated += float(estimated_cost)
    if estimated < 0.05:
        return conservative_cost, None
    observed_ratio = actual / estimated
    projection_ratio = min(1.0, max(0.5, observed_ratio * 1.25))
    return conservative_cost * projection_ratio, observed_ratio


def run_tasks(
    tasks: list[GenerationTask],
    api_key: str,
    output_dir: Path,
    max_spend: float,
    concurrency: int,
    use_ledger: bool,
) -> list[GenerationResult]:
    if max_spend <= 0 or max_spend > HARD_SPEND_CAP_USD:
        raise YogaAudioError(f"--max-spend must be greater than 0 and at most ${HARD_SPEND_CAP_USD:.2f}")

    ledger = load_ledger() if use_ledger else {"model": MODEL, "budgetedSpendUSD": 0.0, "generations": []}
    previous_spend = float(ledger.get("budgetedSpendUSD", 0)) if use_ledger else 0
    if previous_spend > max_spend:
        raise YogaAudioError("Existing ledger spend already exceeds this run's cap")

    completed: list[GenerationResult] = []
    pending: list[GenerationTask] = []
    for task in tasks:
        existing = completed_result(task, ledger, output_dir) if use_ledger else None
        if existing:
            completed.append(existing)
        else:
            pending.append(task)

    conservative_remaining = sum(task.estimated_cost for task in pending)
    if previous_spend + conservative_remaining > max_spend:
        raise YogaAudioError(
            f"Conservative preflight is ${previous_spend + conservative_remaining:.2f}, "
            f"above the ${max_spend:.2f} cap. Reduce the catalog or raise the cap up to ${HARD_SPEND_CAP_USD:.2f}."
        )

    projected_credit_need, observed_ratio = calibrated_credit_projection(conservative_remaining, ledger)
    credits = credit_remaining(api_key)
    if credits is not None and credits + 0.001 < projected_credit_need + CREDIT_RESERVE_USD:
        raise YogaAudioError(
            f"OpenRouter reports about ${credits:.2f} remaining, below the "
            f"${projected_credit_need + CREDIT_RESERVE_USD:.2f} calibrated requirement."
        )
    if observed_ratio is not None and credits is not None:
        print(
            f"Credit preflight: ${credits:.2f} available; same-model generations used "
            f"{observed_ratio:.1%} of their conservative reserve. Holding "
            f"${projected_credit_need:.2f} plus a ${CREDIT_RESERVE_USD:.2f} account buffer.",
            flush=True,
        )

    print(
        f"Resume: {len(completed)} ready; generating {len(pending)} unique audio files "
        f"with {concurrency} workers. Conservative total: ${previous_spend + conservative_remaining:.2f}.",
        flush=True,
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    budgeted_spend = previous_spend
    generated = 0

    for start in range(0, len(pending), concurrency):
        batch_number = start // concurrency
        if batch_number and batch_number % CREDIT_CHECK_INTERVAL_BATCHES == 0:
            conservative_left = sum(task.estimated_cost for task in pending[start:])
            projected_left, _ = calibrated_credit_projection(conservative_left, ledger)
            live_credits = credit_remaining(api_key)
            if live_credits is not None:
                if live_credits + 0.001 < projected_left + CREDIT_RESERVE_USD:
                    raise YogaAudioError(
                        f"Credit checkpoint stopped safely with ${live_credits:.2f} remaining; "
                        f"the calibrated unfinished workload plus buffer is ${projected_left + CREDIT_RESERVE_USD:.2f}. "
                        "Add OpenRouter credit and rerun the same command to resume."
                    )
                print(
                    f"Credit checkpoint: ${live_credits:.2f} available; "
                    f"${projected_left:.2f} calibrated remaining plus ${CREDIT_RESERVE_USD:.2f} buffer.",
                    flush=True,
                )
        batch = pending[start:start + concurrency]
        reserved = sum(task.estimated_cost for task in batch)
        if budgeted_spend + reserved > max_spend + 1e-9:
            raise YogaAudioError("Hard spend cap reached before scheduling the next batch")
        with concurrent.futures.ThreadPoolExecutor(max_workers=len(batch)) as executor:
            futures = [executor.submit(generate_one, task, api_key, output_dir) for task in batch]
            batch_errors: list[str] = []
            for future in concurrent.futures.as_completed(futures):
                try:
                    result = future.result()
                except YogaAudioError as error:
                    batch_errors.append(str(error))
                    continue
                completed.append(result)
                generated += 1
                charged = result.actual_cost if result.actual_cost is not None else result.task.estimated_cost
                budgeted_spend += charged
                if use_ledger:
                    ledger["budgetedSpendUSD"] = round(budgeted_spend, 6)
                    ledger["generations"].append(ledger_item(result))
                    write_json(LEDGER_PATH, ledger)
                print(
                    f"[{len(completed)}/{len(tasks)}] {result.task.instructor} · {result.task.voice} · "
                    f"{result.task.clip_ids[0]} · {result.duration_seconds:.1f}s · "
                    f"budget ${budgeted_spend:.3f}",
                    flush=True,
                )
        if batch_errors:
            raise YogaAudioError(
                "Generation batch failed after recording all completed work:\n- "
                + "\n- ".join(batch_errors)
            )

    print(f"Generated {generated}; ready {len(completed)}; budgeted spend ${budgeted_spend:.3f}.", flush=True)
    return completed


def manifest_from_results(
    results: list[GenerationResult],
    female_voice: str,
    male_voice: str,
    status: str,
    approval_note: str,
) -> dict[str, Any]:
    guidance = load_json(GUIDANCE_PATH)
    clips: list[dict[str, Any]] = []
    for result in results:
        for clip_id in result.task.clip_ids:
            clips.append({
                "id": clip_id,
                "instructor": result.task.instructor,
                "voice": result.task.voice,
                "filename": result.task.filename,
                "durationSeconds": round(result.duration_seconds, 4),
                "sha256": result.sha256,
                "transcript": result.task.transcript,
                "generationID": result.generation_id,
            })
    clips.sort(key=lambda clip: (clip["id"], clip["instructor"]))
    return {
        "schemaVersion": SCHEMA_VERSION,
        "contentVersion": guidance["contentVersion"],
        "status": status,
        "model": MODEL,
        "voices": {"female": female_voice, "male": male_voice},
        "voiceApproval": approval_note,
        "generatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "clips": clips,
    }


def command_catalog(_: argparse.Namespace) -> None:
    transcripts = transcript_catalog()
    tasks = build_tasks(FEMALE_CANDIDATES[0], MALE_CANDIDATES[0], transcripts)
    total = sum(task.estimated_cost for task in tasks)
    total_seconds = sum(estimated_duration(task.transcript) for task in tasks)
    mp3_mebibytes = total_seconds * 96_000 / 8 / (1024 * 1024)
    unique_text = len({entry.text for entry in transcripts})
    print(f"Reviewed transcript IDs: {len(transcripts)}")
    print(f"Unique transcript text: {unique_text}")
    print(f"Bundled manifest rows after two voices: {len(transcripts) * 2}")
    print(f"Unique MP3 generation calls after de-duplication: {len(tasks)}")
    print(f"Estimated narration: {total_seconds / 60:.1f} minutes; about {mp3_mebibytes:.1f} MiB at 96 kbps")
    print(f"Conservative generation reserve: ${total:.2f} (hard cap ${HARD_SPEND_CAP_USD:.2f})")
    print(f"Female audition candidates: {', '.join(FEMALE_CANDIDATES)}")
    print(f"Male audition candidates: {', '.join(MALE_CANDIDATES)}")


def audition_transcript() -> Transcript:
    return Transcript(
        clip_id="audition.guided-yoga",
        kind="opening",
        text=(
            "Welcome to your practice. Stand with your feet at a comfortable distance and let your shoulders soften. "
            "Inhale and feel the ribs widen. Exhale without forcing the breath. "
            "Let steadiness and ease share the work, and remember that you can change the shape at any time."
        ),
    )


def command_audition(arguments: argparse.Namespace) -> None:
    require_billable_confirmation(arguments)
    api_key = require_api_key()
    voices = tuple(arguments.voices or (FEMALE_CANDIDATES + MALE_CANDIDATES))
    invalid = [voice for voice in voices if voice not in FEMALE_CANDIDATES + MALE_CANDIDATES]
    if invalid:
        raise YogaAudioError(f"Unsupported audition voice(s): {', '.join(invalid)}")

    sample = audition_transcript()
    tasks: list[GenerationTask] = []
    for voice in voices:
        instructor = "female" if voice in FEMALE_CANDIDATES else "male"
        tasks.append(GenerationTask(
            instructor=instructor,
            voice=voice,
            transcript=sample.text,
            kind=sample.kind,
            clip_ids=(f"audition.{voice}",),
            filename=f"audition_{voice.lower()}.mp3",
            estimated_cost=estimated_cost(sample.text),
        ))

    output = ARTIFACT_DIR / "auditions"
    # Auditions and the eventual production batch share one ledger so the
    # project-wide spend can never silently exceed the user's cap.
    results = run_tasks(
        tasks, api_key, output, arguments.max_spend, min(arguments.concurrency, len(tasks)), use_ledger=True
    )
    cards = []
    for result in sorted(results, key=lambda item: item.task.voice):
        cards.append(
            f"<section><h2>{html.escape(result.task.voice)} ({result.task.instructor})</h2>"
            f"<audio controls preload='metadata' src='{html.escape(result.task.filename)}'></audio></section>"
        )
    index = (
        "<!doctype html><meta charset='utf-8'><title>ForgeFit yoga voice auditions</title>"
        "<style>body{font:16px -apple-system;margin:2rem;max-width:720px}section{margin:2rem 0}audio{width:100%}</style>"
        "<h1>ForgeFit yoga voice auditions</h1><p>Use headphones and compare calmness, clarity, pacing, and pronunciation.</p>"
        + "".join(cards)
    )
    (output / "index.html").write_text(index, encoding="utf-8")
    print(f"Auditions ready: {output / 'index.html'}")


def command_batch(arguments: argparse.Namespace) -> None:
    require_billable_confirmation(arguments)
    if not arguments.voices_approved.strip():
        raise YogaAudioError("--voices-approved must record the user's audition approval")
    if arguments.female_voice not in FEMALE_CANDIDATES:
        raise YogaAudioError(f"Choose a female voice from: {', '.join(FEMALE_CANDIDATES)}")
    if arguments.male_voice not in MALE_CANDIDATES:
        raise YogaAudioError(f"Choose a male voice from: {', '.join(MALE_CANDIDATES)}")

    api_key = require_api_key()
    tasks = build_tasks(arguments.female_voice, arguments.male_voice)
    results = run_tasks(
        tasks,
        api_key,
        AUDIO_DIR,
        arguments.max_spend,
        arguments.concurrency,
        use_ledger=True,
    )
    manifest = manifest_from_results(
        results,
        arguments.female_voice,
        arguments.male_voice,
        status="generated-unverified",
        approval_note=arguments.voices_approved.strip(),
    )
    write_json(MANIFEST_PATH, manifest)
    print(f"Generated manifest: {MANIFEST_PATH}")
    print("Run `scripts/generate_yoga_audio.py verify` before marking assets approved.")


def expected_manifest_keys() -> set[tuple[str, str]]:
    return {
        (transcript.clip_id, instructor)
        for transcript in transcript_catalog()
        for instructor in ("female", "male")
    }


def command_verify(arguments: argparse.Namespace) -> None:
    manifest = load_json(MANIFEST_PATH)
    if manifest.get("schemaVersion") != SCHEMA_VERSION:
        raise YogaAudioError("Manifest schema is missing or unsupported")
    if manifest.get("model") != MODEL:
        raise YogaAudioError("Manifest model does not match the approved model")
    if manifest.get("contentVersion") != load_json(GUIDANCE_PATH).get("contentVersion"):
        raise YogaAudioError("Manifest was generated from a different content version")
    if not manifest.get("voices", {}).get("female") or not manifest.get("voices", {}).get("male"):
        raise YogaAudioError("Both audition-approved voices must be recorded")
    if not manifest.get("voiceApproval"):
        raise YogaAudioError("Voice audition approval is missing")

    expected = expected_manifest_keys()
    actual: set[tuple[str, str]] = set()
    transcript_by_id = {entry.clip_id: entry.text for entry in transcript_catalog()}
    failures: list[str] = []
    checked_files: set[str] = set()

    for clip in manifest.get("clips", []):
        key = (clip.get("id"), clip.get("instructor"))
        if key in actual:
            failures.append(f"Duplicate manifest row: {key}")
            continue
        actual.add(key)
        if transcript_by_id.get(clip.get("id")) != clip.get("transcript"):
            failures.append(f"Transcript mismatch: {key}")
        filename = clip.get("filename", "")
        path = AUDIO_DIR / filename
        if not path.exists():
            failures.append(f"Missing file: {filename}")
            continue
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != clip.get("sha256"):
            failures.append(f"SHA-256 mismatch: {filename}")
        if filename not in checked_files:
            checked_files.add(filename)
            try:
                probe = probe_audio(path)
                verify_signal(path)
                if probe["codec"] != "mp3":
                    failures.append(f"Unexpected codec {probe['codec']}: {filename}")
                if probe["sample_rate"] != 24_000 or probe["channels"] != 1:
                    failures.append(f"Expected 24 kHz mono: {filename}")
                if not 0.4 < probe["duration"] < 45:
                    failures.append(f"Implausible duration {probe['duration']:.2f}s: {filename}")
                if abs(probe["duration"] - float(clip.get("durationSeconds", 0))) > 0.08:
                    failures.append(f"Duration mismatch: {filename}")
            except YogaAudioError as error:
                failures.append(str(error))

    missing = sorted(expected - actual)
    extra = sorted(actual - expected)
    failures += [f"Missing manifest row: {item}" for item in missing]
    failures += [f"Unexpected manifest row: {item}" for item in extra]
    if failures:
        preview = "\n".join(f"- {failure}" for failure in failures[:50])
        raise YogaAudioError(f"Verification failed with {len(failures)} issue(s):\n{preview}")

    print(
        f"Verified {len(actual)} manifest rows across {len(checked_files)} MP3 files: "
        "exact transcripts, hashes, decodable 24 kHz mono audio, duration, and non-silent signal."
    )
    if arguments.mark_approved:
        if not arguments.listening_approved.strip():
            raise YogaAudioError(
                "--mark-approved requires --listening-approved with the human listening audit note"
            )
        if manifest.get("status") not in {"generated-unverified", "approved"}:
            raise YogaAudioError(f"Cannot approve manifest in status {manifest.get('status')!r}")
        manifest["status"] = "approved"
        manifest["listeningApproval"] = arguments.listening_approved.strip()
        manifest["verifiedAt"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        write_json(MANIFEST_PATH, manifest)
        print("Manifest status is now approved. Manual listening and physical-device audio checks remain release gates.")
    else:
        print("Verification passed. Re-run with --mark-approved after manual spot listening is complete.")


def require_billable_confirmation(arguments: argparse.Namespace) -> None:
    if not arguments.confirm_billable:
        raise YogaAudioError(
            "This command is billable. Re-run with --confirm-billable after reviewing model, voices, and --max-spend."
        )
    if arguments.max_spend > HARD_SPEND_CAP_USD:
        raise YogaAudioError(f"ForgeFit's hard OpenRouter cap is ${HARD_SPEND_CAP_USD:.2f}")


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    commands = root.add_subparsers(dest="command", required=True)

    catalog = commands.add_parser("catalog", help="Show transcript and cost workload without network calls")
    catalog.set_defaults(handler=command_catalog)

    audition = commands.add_parser("audition", help="Generate the bounded voice-comparison pack")
    audition.add_argument("--voices", nargs="*", help="Subset of the eight curated candidates")
    audition.add_argument("--max-spend", type=float, default=1.0)
    audition.add_argument("--concurrency", type=int, choices=range(1, 5), default=4)
    audition.add_argument("--confirm-billable", action="store_true")
    audition.set_defaults(handler=command_audition)

    batch = commands.add_parser("batch", help="Generate both complete offline narration libraries")
    batch.add_argument("--female-voice", required=True)
    batch.add_argument("--male-voice", required=True)
    batch.add_argument(
        "--voices-approved",
        required=True,
        help="Short audit note recording who approved the audition and when",
    )
    batch.add_argument("--max-spend", type=float, default=HARD_SPEND_CAP_USD)
    batch.add_argument("--concurrency", type=int, choices=range(1, 5), default=4)
    batch.add_argument("--confirm-billable", action="store_true")
    batch.set_defaults(handler=command_batch)

    verify = commands.add_parser("verify", help="Verify every manifest row and MP3 without API calls")
    verify.add_argument("--mark-approved", action="store_true")
    verify.add_argument(
        "--listening-approved",
        default="",
        help="Human listening audit note required with --mark-approved",
    )
    verify.set_defaults(handler=command_verify)
    return root


def main() -> int:
    try:
        arguments = parser().parse_args()
        arguments.handler(arguments)
        return 0
    except YogaAudioError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
